/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RomeRouteImport } from './routes/rome'
import { Route as GalaxyRouteImport } from './routes/galaxy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RomeTourRouteImport } from './routes/rome.tour'

const RomeRoute = RomeRouteImport.update({
  id: '/rome',
  path: '/rome',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxyRoute = GalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RomeTourRoute = RomeTourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => RomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/galaxy': typeof GalaxyRoute
  '/rome': typeof RomeRouteWithChildren
  '/rome/tour': typeof RomeTourRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/galaxy': typeof GalaxyRoute
  '/rome': typeof RomeRouteWithChildren
  '/rome/tour': typeof RomeTourRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/galaxy': typeof GalaxyRoute
  '/rome': typeof RomeRouteWithChildren
  '/rome/tour': typeof RomeTourRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/auth' | '/galaxy' | '/rome' | '/rome/tour'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/auth' | '/galaxy' | '/rome' | '/rome/tour'
  id: '__root__' | '/' | '/admin' | '/auth' | '/galaxy' | '/rome' | '/rome/tour'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  GalaxyRoute: typeof GalaxyRoute
  RomeRoute: typeof RomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rome': {
      id: '/rome'
      path: '/rome'
      fullPath: '/rome'
      preLoaderRoute: typeof RomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxy': {
      id: '/galaxy'
      path: '/galaxy'
      fullPath: '/galaxy'
      preLoaderRoute: typeof GalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rome/tour': {
      id: '/rome/tour'
      path: '/tour'
      fullPath: '/rome/tour'
      preLoaderRoute: typeof RomeTourRouteImport
      parentRoute: typeof RomeRoute
    }
  }
}

interface RomeRouteChildren {
  RomeTourRoute: typeof RomeTourRoute
}

const RomeRouteChildren: RomeRouteChildren = {
  RomeTourRoute: RomeTourRoute,
}

const RomeRouteWithChildren = RomeRoute._addFileChildren(RomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  GalaxyRoute: GalaxyRoute,
  RomeRoute: RomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
