/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalaxyRouteImport } from './routes/galaxy'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RomeIndexRouteImport } from './routes/rome.index'
import { Route as RomeTourRouteImport } from './routes/rome.tour'

const GalaxyRoute = GalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RomeIndexRoute = RomeIndexRouteImport.update({
  id: '/rome/',
  path: '/rome/',
  getParentRoute: () => rootRouteImport,
} as any)
const RomeTourRoute = RomeTourRouteImport.update({
  id: '/rome/tour',
  path: '/rome/tour',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/galaxy': typeof GalaxyRoute
  '/rome/tour': typeof RomeTourRoute
  '/rome/': typeof RomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/galaxy': typeof GalaxyRoute
  '/rome/tour': typeof RomeTourRoute
  '/rome': typeof RomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/galaxy': typeof GalaxyRoute
  '/rome/tour': typeof RomeTourRoute
  '/rome/': typeof RomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/downloads'
    | '/galaxy'
    | '/rome/tour'
    | '/rome/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/downloads'
    | '/galaxy'
    | '/rome/tour'
    | '/rome'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/downloads'
    | '/galaxy'
    | '/rome/tour'
    | '/rome/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DownloadsRoute: typeof DownloadsRoute
  GalaxyRoute: typeof GalaxyRoute
  RomeTourRoute: typeof RomeTourRoute
  RomeIndexRoute: typeof RomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/galaxy': {
      id: '/galaxy'
      path: '/galaxy'
      fullPath: '/galaxy'
      preLoaderRoute: typeof GalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rome/': {
      id: '/rome/'
      path: '/rome'
      fullPath: '/rome/'
      preLoaderRoute: typeof RomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rome/tour': {
      id: '/rome/tour'
      path: '/rome/tour'
      fullPath: '/rome/tour'
      preLoaderRoute: typeof RomeTourRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DownloadsRoute: DownloadsRoute,
  GalaxyRoute: GalaxyRoute,
  RomeTourRoute: RomeTourRoute,
  RomeIndexRoute: RomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
